### PR TITLE
ci: update pre-commit hooks and add workflow

### PR DESCRIPTION
**Pull request by benwandrew**
# Description

update pre-commit config file and add workflow to run it upon PR.

# Type of change

- **ci**: Changes to our CI configuration files and scripts (i.e., those in the .github directory)

### CODE REVIEW

**Comment by TheLemonPig** [comment]
It looks like the pre-commit hooks are failing. I would know how to fix most of these by commit the changes, but I am not sure why Mypy is failing

**Review by TheLemonPig — CHANGES_REQUESTED** [review]
TODO: Get Pre-commit hooks to pass

**Comment by benwandrew** [comment]
@listar2000 looks like we still have some outstanding `mypy` issues. would you mind taking a peek? i added you to this repo with write access.

**Comment by listar2000** [comment]
> @listar2000 looks like we still have some outstanding `mypy` issues. would you mind taking a peek? i added you to this repo with write access.

Sure. This is expected since there might always be new errors popping out. Will take a look.

**Comment by benwandrew** [comment]
> > @listar2000 looks like we still have some outstanding `mypy` issues. would you mind taking a peek? i added you to this repo with write access.
> 
> Sure. This is expected since there might always be new errors popping out. Will take a look.

bumping this ;)

**Comment by listar2000** [comment]
@benwandrew This PR can be resolved once the other PR #11 is accepted (it passes all precommit tests now).

**Comment by benwandrew** [comment]
@musslick @younesStrittmatter 

> TODO: Get Pre-commit hooks to pass

@TheLemonPig these now pass! can you please approve when you get a chance?

**Review by listar2000 — APPROVED** [review]

**Review by TheLemonPig — APPROVED** [review]

**Pull request merged**
